name: docs

on:
  push:
    branches:
      - 'master'
    paths:
      - 'pysr/**'
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'setup.py'
      - 'README.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: "Install packages for docs building"
        run: pip install -r docs/requirements.txt
      - name: "Install PySR"
        run: pip install -e .
      - name: "Build API docs"
        run: cd docs && ./gen_docs.sh
      - name: "Deploy documentation"
        run: mkdocs gh-deploy --force